# Generated by Django 5.1.6 on 2025-03-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.CharField(max_length=255)),
                ('english', models.CharField(max_length=255)),
                ('vietnamese', models.CharField(max_length=255)),
                ('chinese_traditional', models.CharField(max_length=255)),
                ('chinese_simplified', models.CharField(max_length=255)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
