# Generated by Django 5.1.6 on 2025-05-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_keywordsuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlighttext',
            name='file',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
        migrations.RemoveField(
            model_name='highlighttext',
            name='user',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.DeleteModel(
            name='HighlightText',
        ),
    ]
