# Generated by Django 5.1.6 on 2025-05-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_highlighttext_file_remove_fileupload_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonKeyword',
        ),
    ]
