# Generated by Django 5.1.6 on 2025-05-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_keywordsuggestion_reviewed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatedfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='translatedfile',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='translatedfile',
            name='translated_file',
        ),
        migrations.AddField(
            model_name='translatedfile',
            name='original_file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='translatedfile',
            name='original_file_url',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='translatedfile',
            name='translated_file_url',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='translatedfile',
            name='file_type',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='translatedfile',
            name='original_language',
            field=models.CharField(default='', max_length=10),
        ),
    ]
